### ISSUE TITLE
False alarms because using the hooks?

### ISSUE THREAD

**Issue by zaszlo** [angel333/certbot-he-hook#4]
I have received an alert from Let's Encrypt Expiry Bot <expiry@letsencrypt.org> stating that one of my domain's validity is expiring in 19 days, but as I check with `certbot certificates` and from ssllabs.com it has almost 3 months of validity as it should have. So what could be causing the false alarm? The only thing that came to my mind is the hook. Are there others receiving false alarms like this? Thoughts?

**Comment by higuita** [comment]
probably a old certificate that you left unused after migrating to the domain validation?
